// apps/testing/qwik/src/components/cap-widget-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import { CapWidget, type CapWidgetHandle, type RenderParameters } from "@better-captcha/qwik/provider/cap-widget";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const CapWidgetTest = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<CapWidgetHandle>();
	const options = useSignal<RenderParameters>({});
	const response = useSignal<string | null>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="cap-widget"
				component={CapWidget}
				controller={controller}
				options={options.value}
				endpoint="https://captcha.gurl.eu.org/api/"
				onSolve$={handleSolve$}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.execute();
				}}
			>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() || "No response";
					response.value = captchaResponse;
				}}
			>
				Get Response
			</button>
			{response.value && <p id="captcha-response">{response.value}</p>}
		</div>
	);
});

// apps/testing/react/src/cap-widget-test.tsx
import { type RenderParameters, CapWidget, type CapWidgetHandle } from "@better-captcha/react/provider/cap-widget";
import { useRef, useState } from "react";
import { RenderCaptcha, type CaptchaComponentMode } from "./render-captcha";

export function CapWidgetTest({ mode }: { mode: CaptchaComponentMode }) {
	const capWidgetRef = useRef<CapWidgetHandle>(null);
	const [options, setOptions] = useState<RenderParameters>(() => {
		return {};
	});
	const [response, setResponse] = useState<string | null>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = capWidgetRef.current?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha mode={mode} provider="cap-widget" component={CapWidget} 
				ref={capWidgetRef} 
				options={options} 
				endpoint="https://captcha.gurl.eu.org/api/" 
				onSolve={handleSolve}
			/>
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => capWidgetRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => capWidgetRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => capWidgetRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => capWidgetRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			{response && <p id="captcha-response">{response}</p>}
		</div>
	);
}
