// apps/testing/qwik/src/components/captcha-fox-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import { CaptchaFox, type CaptchaFoxHandle, type RenderParameters } from "@better-captcha/qwik/provider/captcha-fox";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const CaptchaFoxTest = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<CaptchaFoxHandle>();
	const options = useSignal<Omit<RenderParameters, "sitekey">>({
		theme: "light",
		mode: "inline",
	});
	const response = useSignal<string | null>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="captcha-fox"
				component={CaptchaFox}
				controller={controller}
				options={options.value}
				sitekey="sk_11111111000000001111111100000000"
				onSolve$={handleSolve$}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() || "No response";
					response.value = captchaResponse;
				}}
			>
				Get Response
			</button>
			<button type="button" onClick$={() => controller.value?.execute()}>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const themes = ["light", "dark", "auto"];
					const currentTheme = options.value.theme;
					const currentIndex = themes.indexOf(typeof currentTheme === "string" ? currentTheme : "light");
					const nextIndex = (currentIndex + 1) % themes.length;
					options.value = { ...options.value, theme: themes[nextIndex] as RenderParameters["theme"] };
				}}
			>
				Change Theme
			</button>
			{response.value && <p id="captcha-response">{response.value}</p>}
		</div>
	);
});

// apps/testing/react/src/captcha-fox-test.tsx
import { CaptchaFox, type CaptchaFoxHandle, type RenderParameters } from "@better-captcha/react/provider/captcha-fox";
import { useRef, useState } from "react";
import { RenderCaptcha, type CaptchaComponentMode } from "./render-captcha";

export function CaptchaFoxTest({ mode }: { mode: CaptchaComponentMode }) {
	const captchaFoxRef = useRef<CaptchaFoxHandle>(null);
	const [options, setOptions] = useState(
		(): Omit<RenderParameters, "sitekey"> => ({
			theme: "light",
			mode: "inline",
		}),
	);
	const [response, setResponse] = useState<string | null>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = captchaFoxRef.current?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha mode={mode} provider="captcha-fox" component={CaptchaFox} ref={captchaFoxRef} sitekey="sk_11111111000000001111111100000000" options={options} onSolve={handleSolve} />
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => captchaFoxRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => captchaFoxRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => captchaFoxRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => captchaFoxRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			<button
				type="button"
				onClick={() => {
					const themes = ["light", "dark", "auto"];
					const currentIndex = themes.indexOf(options.theme as string);
					const nextIndex = (currentIndex + 1) % themes.length;
					setOptions({ ...options, theme: themes[nextIndex] as RenderParameters["theme"] });
				}}
			>
				Change Theme
			</button>
			{response && <p id="captcha-response">{response}</p>}
		</div>
	);
}
