// apps/testing/lit/src/geetest-test.ts
import { Geetest, type GeetestHandle } from "@better-captcha/lit/provider/geetest";
import { html, LitElement } from "lit";
import { customElement, state } from "lit/decorators.js";
import { createRef, type Ref, ref } from "lit/directives/ref.js";

Geetest;

type GeetestCaptchaElement = LitElement & { getHandle: () => GeetestHandle };

@customElement("geetest-test")
export class GeetestTest extends LitElement {
	private captchaRef: Ref<GeetestCaptchaElement> = createRef();

	@state()
	private options = {
		language: "eng",
	};

	@state()
	private response: ReturnType<GeetestHandle["getResponse"]> | null = null;

	@state()
	private solved = false;

	protected createRenderRoot() {
		return this;
	}

	private handleSolve = (token: ReturnType<GeetestHandle["getResponse"]>) => {
		this.solved = true;
		console.log("Captcha solved with token:", token);
	};

	private handleDestroy() {
		this.captchaRef.value?.getHandle()?.destroy();
	}

	private handleReset() {
		this.captchaRef.value?.getHandle()?.reset();
	}

	private handleExecute() {
		this.captchaRef.value?.getHandle()?.execute();
	}

	private async handleRender() {
		await this.captchaRef.value?.getHandle()?.render();
	}

	private handleGetResponse() {
		const captchaResponse = this.captchaRef.value?.getHandle()?.getResponse() || "No response";
		this.response = captchaResponse;
	}

	render() {
		return html`
			<div>
				<geetest-captcha
					${ref(this.captchaRef)}
					sitekey="08649cc61c7078689263ebf78225d616"
					.options=${this.options}
					.onSolve=${this.handleSolve}
				></geetest-captcha>
				${this.solved ? html`<p id="captcha-solved">Captcha Solved!</p>` : ""}
				<button type="button" @click=${this.handleDestroy}>Destroy</button>
				<button type="button" @click=${this.handleReset}>Reset</button>
				<button type="button" @click=${this.handleExecute}>Execute</button>
				<button type="button" @click=${this.handleRender}>Render</button>
				<button type="button" @click=${this.handleGetResponse}>Get Response</button>
				${this.response ? html`<p id="captcha-response">${JSON.stringify(this.response, null, "\t")}</p>` : ""}
			</div>
		`;
	}
}

declare global {
	interface HTMLElementTagNameMap {
		"geetest-test": GeetestTest;
	}
}

// apps/testing/react/src/geetest-test.tsx
import { Geetest, type GeetestHandle } from "@better-captcha/react/provider/geetest";
import { useRef, useState } from "react";

export function GeetestTest() {
	const geetestRef = useRef<GeetestHandle>(null);
	const [response, setResponse] = useState<string | null>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = geetestRef.current?.getResponse() || "No response";
    if (captchaResponse) {
		  setResponse(JSON.stringify(captchaResponse, null, '\t'));
    }
	};

	const handleSolve = (token: ReturnType<GeetestHandle["getResponse"]>) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<Geetest
				ref={geetestRef} 
        sitekey="08649cc61c7078689263ebf78225d616"
        // onSolve={handleSolve}
        options={{ language: 'eng'}}
			/>
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => geetestRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => geetestRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => geetestRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => geetestRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			{response && <p id="captcha-response">{response}</p>}
		</div>
	);
}
