// apps/testing/solidjs/src/components/geetest-test.tsx
import { createCaptchaController } from "@better-captcha/solidjs";
import {
	Geetest,
	type GeetestHandle,
	type GeetestSolveResponse,
	type RenderParameters,
} from "@better-captcha/solidjs/provider/geetest";
import { createSignal } from "solid-js";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export function GeetestTest(props: { mode: CaptchaComponentMode }) {
	const controller = createCaptchaController<GeetestHandle>();
	const [options, _setOptions] = createSignal<RenderParameters>({
		language: "eng",
	});
	const [response, setResponse] = createSignal<string | null>(null);
	const [solved, setSolved] = createSignal<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = controller.handle()?.getResponse() || "No response";
		setResponse(JSON.stringify(captchaResponse, null, "\t"));
	};

	const handleSolve = (token: GeetestSolveResponse) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha
				mode={props.mode}
				provider="geetest"
				component={Geetest}
				controller={controller}
				sitekey="647f5ed2ed8acb4be36784e01556bb71"
				options={options()}
				onSolve={handleSolve}
			/>
			{solved() && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => controller.handle()?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => controller.handle()?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => controller.handle()?.execute()}>
				Execute
			</button>
			<button type="button" onClick={async () => await controller.handle()?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			{response() && <p id="captcha-response">{response()}</p>}
		</div>
	);
}

// apps/testing/react/src/geetest-test.tsx
import { Geetest, type GeetestHandle, type GeetestSolveResponse } from "@better-captcha/react/provider/geetest";
import { useRef, useState } from "react";
import { RenderCaptcha, type CaptchaComponentMode } from "./render-captcha";

export function GeetestTest({ mode }: { mode: CaptchaComponentMode }) {
	const geetestRef = useRef<GeetestHandle>(null);
	const [response, setResponse] = useState<ReturnType<GeetestHandle["getResponse"]> | null>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = geetestRef.current?.getResponse() ?? false;
		setResponse(captchaResponse);
	};

	const handleSolve = (token: GeetestSolveResponse) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha mode={mode} provider="geetest" component={Geetest}
				ref={geetestRef}
				sitekey="647f5ed2ed8acb4be36784e01556bb71"
				onSolve={handleSolve}
				options={{ language: "eng" }}
			/>
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => geetestRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => geetestRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => geetestRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => geetestRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			{response && <p id="captcha-response">{JSON.stringify(response, null, "\t")}</p>}
		</div>
	);
}
