// apps/testing/qwik/src/components/hcaptcha-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import { HCaptcha, type HCaptchaHandle, type RenderParameters } from "@better-captcha/qwik/provider/hcaptcha";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const HCaptchaTest = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<HCaptchaHandle>();
	const options = useSignal<Omit<RenderParameters, "sitekey">>({
		theme: "light",
		size: "normal",
	});
	const response = useSignal<string | null>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="hcaptcha"
				component={HCaptcha}
				controller={controller}
				options={options.value}
				sitekey="10000000-ffff-ffff-ffff-000000000001"
				onSolve$={handleSolve$}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.execute();
				}}
			>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() || "No response";
					response.value = captchaResponse;
				}}
			>
				Get Response
			</button>
			<button
				type="button"
				onClick$={() => {
					const themes = ["light", "dark"];
					const currentIndex = themes.indexOf(options.value.theme || "light");
					const nextIndex = (currentIndex + 1) % themes.length;
					options.value = { ...options.value, theme: themes[nextIndex] as RenderParameters["theme"] };
				}}
			>
				Change Theme
			</button>
			{response.value && <p id="captcha-response">{response.value}</p>}
		</div>
	);
});

// apps/testing/react/src/hcaptcha-test.tsx
import { HCaptcha, type HCaptchaHandle, type RenderParameters } from "@better-captcha/react/provider/hcaptcha";
import { useRef, useState } from "react";
import { RenderCaptcha, type CaptchaComponentMode } from "./render-captcha";

export function HCaptchaTest({ mode }: { mode: CaptchaComponentMode }) {
	const turnstileRef = useRef<HCaptchaHandle>(null);
	const [options, setOptions] = useState(
		(): Omit<RenderParameters, "sitekey"> => ({
			theme: "light",
			size: "normal",
		}),
	);
	const [response, setResponse] = useState<string | null>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = turnstileRef.current?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha mode={mode} provider="hcaptcha" component={HCaptcha} ref={turnstileRef} sitekey="10000000-ffff-ffff-ffff-000000000001" options={options} onSolve={handleSolve} />
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => turnstileRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => turnstileRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => turnstileRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => turnstileRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			<button
				type="button"
				onClick={() => {
					const themes = ["light", "dark", "auto"];
					const currentIndex = themes.indexOf(options.theme ?? "light");
					const nextIndex = (currentIndex + 1) % themes.length;
					setOptions({ ...options, theme: themes[nextIndex] as RenderParameters["theme"] });
				}}
			>
				Change Theme
			</button>
			{response && <p id="captcha-response">{response}</p>}
		</div>
	);
}
