// apps/testing/lit/src/prosopo-test.ts
import { Prosopo, type ProsopoHandle } from "@better-captcha/lit/provider/prosopo";
import { html, LitElement } from "lit";
import { customElement, state } from "lit/decorators.js";
import { createRef, type Ref, ref } from "lit/directives/ref.js";

Prosopo;

type ProsopoCaptchaElement = LitElement & { getHandle: () => ProsopoHandle };

@customElement("prosopo-test")
export class ProsopoTest extends LitElement {
	private captchaRef: Ref<ProsopoCaptchaElement> = createRef();

	@state()
	private theme: "light" | "dark" | "auto" = "light";

	@state()
	private response: string | null = null;

	@state()
	private solved = false;

	protected createRenderRoot() {
		return this;
	}

	private handleSolve = (token: string) => {
		this.solved = true;
		console.log("Captcha solved with token:", token);
	};

	private handleDestroy() {
		this.captchaRef.value?.getHandle()?.destroy();
	}

	private handleReset() {
		this.captchaRef.value?.getHandle()?.reset();
	}

	private handleExecute() {
		this.captchaRef.value?.getHandle()?.execute();
	}

	private async handleRender() {
		await this.captchaRef.value?.getHandle()?.render();
	}

	private handleGetResponse() {
		const captchaResponse = this.captchaRef.value?.getHandle()?.getResponse() || "No response";
		this.response = captchaResponse;
	}

	private handleChangeTheme() {
		const themes = ["light", "dark", "auto"] as const;
		const currentIndex = themes.indexOf(this.theme);
		const nextIndex = (currentIndex + 1) % themes.length;
		this.theme = themes[nextIndex];
	}

	render() {
		const options = {
			theme: this.theme,
			callback: (response: string) => {
				console.log("Prosopo CAPTCHA verified:", response);
				this.response = response;
			},
			"error-callback": (error: Error) => {
				console.error("Prosopo CAPTCHA error:", error);
			},
		};

		return html`
			<div>
				<prosopo-captcha
					${ref(this.captchaRef)}
					sitekey="no_test_site_key"
					.options=${options}
					.onSolve=${this.handleSolve}
				></prosopo-captcha>
				${this.solved ? html`<p id="captcha-solved">Captcha Solved!</p>` : ""}
				<button type="button" @click=${this.handleGetResponse}>Get Response</button>
				<button type="button" @click=${this.handleReset}>Reset</button>
				<button type="button" @click=${this.handleExecute}>Execute</button>
				<button type="button" @click=${this.handleRender}>Render</button>
				<button type="button" @click=${this.handleChangeTheme}>Change Theme</button>
				<button type="button" @click=${this.handleDestroy}>Destroy</button>
				${this.response ? html`<p id="captcha-response">${this.response}</p>` : ""}
			</div>
		`;
	}
}

declare global {
	interface HTMLElementTagNameMap {
		"prosopo-test": ProsopoTest;
	}
}

// apps/testing/react/src/prosopo-test.tsx
import { Prosopo, type ProsopoHandle } from "@better-captcha/react/provider/prosopo";
import { useRef, useState } from "react";

export function ProsopoTest() {
	const captchaRef = useRef<ProsopoHandle>(null);
	const [response, setResponse] = useState<string>("");
	const [theme, setTheme] = useState<"light" | "dark" | "auto">("light");
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = captchaRef.current?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<h2>Prosopo Test</h2>

			<div>
				<Prosopo
					ref={captchaRef}
					sitekey="no_test_site_key"
					options={{
						theme,
						callback: (response) => {
							console.log("Prosopo CAPTCHA verified:", response);
							setResponse(response);
						},
						"error-callback": (error) => {
							console.error("Prosopo CAPTCHA error:", error);
						},
					}}
					onSolve={handleSolve}
				/>
				{solved && <p id="captcha-solved">Captcha Solved!</p>}
			</div>

			<div>
				<button type="button" onClick={handleGetResponse}>
					Get Response
				</button>
				<button type="button" onClick={() => captchaRef.current?.reset()}>
					Reset
				</button>
				<button type="button" onClick={() => captchaRef.current?.execute()}>
					Execute
				</button>
				<button type="button" onClick={() => captchaRef.current?.render()}>
					Render
				</button>
				<button
					type="button"
					onClick={() => {
						const themes = ["light", "dark", "auto"];
						const currentIndex = themes.indexOf(theme || "auto");
						const nextIndex = (currentIndex + 1) % themes.length;
						setTheme(themes[nextIndex] as typeof theme);
					}}
				>
					Change Theme
				</button>
				<button type="button" onClick={() => captchaRef.current?.destroy()}>
					Destroy
				</button>
			</div>

			{response && <p id="captcha-response">{response}</p>}
		</div>
	);
}
