// apps/testing/qwik/src/components/recaptcha-v3-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import { ReCaptchaV3, type ReCaptchaV3Handle, type RenderParameters } from "@better-captcha/qwik/provider/recaptcha-v3";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const RecaptchaV3Test = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<ReCaptchaV3Handle>();
	const options = useSignal<RenderParameters>({
		action: "submit",
	});
	const response = useSignal<string | null>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="recaptcha-v3"
				component={ReCaptchaV3}
				controller={controller}
				options={options.value}
				sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
				onSolve$={handleSolve$}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.execute();
				}}
			>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() || "No response";
					response.value = captchaResponse;
				}}
			>
				Get Response
			</button>
			<button
				type="button"
				onClick$={() => {
					const actions = ["submit", "login", "register"];
					const currentIndex = actions.indexOf(options.value.action);
					const nextIndex = (currentIndex + 1) % actions.length;
					options.value = { action: actions[nextIndex] };
				}}
			>
				Change Action
			</button>
			{response.value && <p id="captcha-response">{response.value}</p>}
		</div>
	);
});

// apps/testing/react/src/recaptcha-v3-test.tsx
import { ReCaptchaV3, type ReCaptchaV3Handle, type RenderParameters } from "@better-captcha/react/provider/recaptcha-v3";
import { useRef, useState } from "react";
import { RenderCaptcha, type CaptchaComponentMode } from "./render-captcha";

export function RecaptchaV3Test({ mode }: { mode: CaptchaComponentMode }) {
	const recaptchaRef = useRef<ReCaptchaV3Handle>(null);
	const [options, setOptions] = useState<RenderParameters>({
		action: "submit",
	});
	const [response, setResponse] = useState<string | null>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = recaptchaRef.current?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha mode={mode} provider="recaptcha-v3" component={ReCaptchaV3} ref={recaptchaRef} sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI" options={options} onSolve={handleSolve} />
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => recaptchaRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => recaptchaRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => recaptchaRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => recaptchaRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			<button
				type="button"
				onClick={() => {
					const actions = ["submit", "login", "register"];
					const currentIndex = actions.indexOf(options.action);
					const nextIndex = (currentIndex + 1) % actions.length;
					setOptions({ action: actions[nextIndex] ?? "submit" });
				}}
			>
				Change Action
			</button>
			{response && <p id="captcha-response">{response}</p>}
		</div>
	);
}
