// apps/testing/vue/src/components/RecaptchaV3Test.vue
<template>
	<div>
		<h3>reCAPTCHA v3 Test</h3>
		<ReCaptchaV3
			ref="captchaRef"
			sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
			:options="options"
			@ready="onReady"
			@error="onError"
			@solve="onSolve"
		/>
		<p v-if="solved" id="captcha-solved">Captcha Solved!</p>
		<div style="margin-top: 10px">
			<button type="button" @click="handleDestroy">Destroy</button>
			<button type="button" @click="handleReset">Reset</button>
			<button type="button" @click="handleExecute">Execute</button>
			<button type="button" @click="handleRender">Render</button>
			<button type="button" @click="handleGetResponse">Get Response</button>
			<button type="button" @click="handleChangeAction">Change Action</button>
		</div>
		<p v-if="response" id="captcha-response">{{ response }}</p>
		<p v-if="error" style="color: red">Error: {{ error.message }}</p>
	</div>
</template>

<script setup lang="ts">
	import { ReCaptchaV3, type ReCaptchaV3Handle, type RenderParameters } from "@better-captcha/vue/provider/recaptcha-v3";
	import { ref } from "vue";

	const captchaRef = ref<ReCaptchaV3Handle | null>(null);
	const response = ref<string | null>(null);
	const error = ref<Error | null>(null);
	const solved = ref<boolean>(false);

	const options = ref<RenderParameters>({
		action: "submit",
	});

	const onReady = (handle: ReCaptchaV3Handle) => {
		console.log("Captcha ready!", handle);
	};

	const onError = (err: Error) => {
		error.value = err;
		console.error("Captcha error:", err);
	};

	const onSolve = (token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	};

	const handleDestroy = () => {
		captchaRef.value?.destroy();
	};

	const handleReset = () => {
		captchaRef.value?.reset();
		response.value = null;
	};

	const handleExecute = async () => {
		await captchaRef.value?.execute();
	};

	const handleRender = async () => {
		await captchaRef.value?.render();
	};

	const handleGetResponse = () => {
		const captchaResponse = captchaRef.value?.getResponse() || "No response";
		response.value = captchaResponse;
	};

	const handleChangeAction = () => {
		const actions = ["submit", "login", "register"];
		const currentIndex = actions.indexOf(options.value.action);
		const nextIndex = (currentIndex + 1) % actions.length;
		options.value = { action: actions[nextIndex] };
	};
</script>

// apps/testing/lit/src/recaptcha-v3-test.ts
import { ReCaptchaV3, type ReCaptchaV3Handle } from "@better-captcha/lit/provider/recaptcha-v3";
import { html, LitElement } from "lit";
import { customElement, state } from "lit/decorators.js";
import { createRef, type Ref, ref } from "lit/directives/ref.js";

ReCaptchaV3;

type ReCaptchaV3CaptchaElement = LitElement & { getHandle: () => ReCaptchaV3Handle };

@customElement("recaptcha-v3-test")
export class RecaptchaV3Test extends LitElement {
	private captchaRef: Ref<ReCaptchaV3CaptchaElement> = createRef();

	@state()
	private options = {
		action: "submit",
	};

	@state()
	private response: string | null = null;

	@state()
	private solved = false;

	protected createRenderRoot() {
		return this;
	}

	private handleSolve = (token: string) => {
		this.solved = true;
		console.log("Captcha solved with token:", token);
	};

	private handleDestroy() {
		this.captchaRef.value?.getHandle()?.destroy();
	}

	private handleReset() {
		this.captchaRef.value?.getHandle()?.reset();
	}

	private handleExecute() {
		this.captchaRef.value?.getHandle()?.execute();
	}

	private async handleRender() {
		await this.captchaRef.value?.getHandle()?.render();
	}

	private handleGetResponse() {
		const captchaResponse = this.captchaRef.value?.getHandle()?.getResponse() || "No response";
		this.response = captchaResponse;
	}

	private handleChangeAction() {
		const actions = ["submit", "login", "register"];
		const currentIndex = actions.indexOf(this.options.action);
		const nextIndex = (currentIndex + 1) % actions.length;
		this.options = { action: actions[nextIndex] };
	}

	render() {
		return html`
			<div>
				<recaptcha-v3-captcha
					${ref(this.captchaRef)}
					sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
					.options=${this.options}
					.onSolve=${this.handleSolve}
				></recaptcha-v3-captcha>
				${this.solved ? html`<p id="captcha-solved">Captcha Solved!</p>` : ""}
				<button type="button" @click=${this.handleDestroy}>Destroy</button>
				<button type="button" @click=${this.handleReset}>Reset</button>
				<button type="button" @click=${this.handleExecute}>Execute</button>
				<button type="button" @click=${this.handleRender}>Render</button>
				<button type="button" @click=${this.handleGetResponse}>Get Response</button>
				<button type="button" @click=${this.handleChangeAction}>Change Action</button>
				${this.response ? html`<p id="captcha-response">${this.response}</p>` : ""}
			</div>
		`;
	}
}

declare global {
	interface HTMLElementTagNameMap {
		"recaptcha-v3-test": RecaptchaV3Test;
	}
}
