// packages/solidjs/src/base-captcha.tsx
import type { CaptchaHandle, CaptchaState, Provider, ProviderConfig, WidgetId } from "@better-captcha/core";
import { cleanup } from "@better-captcha/core/utils/lifecycle";
import { batch, createEffect, createMemo, createSignal, type JSX, onCleanup, onMount, splitProps } from "solid-js";
import type { CaptchaProps } from "./index";

export function createCaptchaComponent<
	TOptions = unknown,
	THandle extends CaptchaHandle = CaptchaHandle,
	TProvider extends Provider<ProviderConfig, TOptions, THandle> = Provider<ProviderConfig, TOptions, THandle>,
>(ProviderClass: new (sitekeyOrEndpoint: string) => TProvider) {
	return function CaptchaComponent(allProps: CaptchaProps<TOptions, THandle>): JSX.Element {
		const [props, divProps] = splitProps(allProps, [
			"sitekey",
			"endpoint",
			"options",
			"class",
			"style",
			"autoRender",
			"onReady",
			"onError",
			"controller",
		]);

		const value = props.endpoint ?? props.sitekey;
		if (!value) {
			throw new Error("Either 'sitekey' or 'endpoint' prop must be provided");
		}
		const provider = createMemo(() => new ProviderClass(value));
		const [elementRef, setElementRef] = createSignal<HTMLDivElement>();
		const [widgetId, setWidgetId] = createSignal<WidgetId | null>(null);
		const autoRender = () => props.autoRender ?? true;
		const [state, setState] = createSignal<CaptchaState>({
			loading: autoRender(),
			error: null,
			ready: false,
		});

		let containerRef: HTMLDivElement | null = null;
		let isRendering = false;
		let hasRendered = false;
		let pendingRender = false;

		const performCleanup = () => {
			cleanup(provider(), widgetId(), containerRef);
			containerRef = null;
			batch(() => {
				setWidgetId(null);
			});
		};

		const renderCaptcha = async () => {
			const element = elementRef();
			const currentProvider = provider();
			const options = props.options;

			if (!element) return;

			if (isRendering) {
				pendingRender = true;
				return;
			}

			isRendering = true;
			pendingRender = false;

			performCleanup();

			batch(() => {
				setWidgetId(null);
				setState({ loading: true, error: null, ready: false });
			});

			try {
				await currentProvider.init();

				const container = document.createElement("div");
				containerRef = container;
				element.appendChild(container);

				const id = await currentProvider.render(container, options);

				batch(() => {
					setWidgetId(id ?? null);
					setState({ loading: false, error: null, ready: true });
				});
			} catch (error) {
				const err = error instanceof Error ? error : new Error(String(error));
				console.error("[better-captcha] render:", err);
				batch(() => {
					setState({ loading: false, error: err, ready: false });
				});
				props.onError?.(err);
			} finally {
				isRendering = false;
				if (pendingRender) {
					pendingRender = false;
					queueMicrotask(() => {
						void renderCaptcha();
					});
				}
			}
		};

		onMount(() => {
			if (autoRender()) {
				void renderCaptcha();
			}
		});

		createEffect(() => {
			const element = elementRef();
			const shouldAutoRender = autoRender();
			props.sitekey;
			props.endpoint;
			props.options;

			if (!element || !hasRendered) return;

			if (shouldAutoRender) {
				void renderCaptcha();
			}

			onCleanup(() => {
				performCleanup();
			});
		});

		createEffect(() => {
			if (state().ready) {
				hasRendered = true;
			}
		});

		const baseHandle = createMemo(() => {
			const id = widgetId();
			if (id == null) return null;
			return provider().getHandle(id) as THandle;
		});

		const handle = createMemo(() => {
			const id = widgetId();
			const base = baseHandle();
			if (!base || id == null) {
				return {
					execute: async () => {},
					reset: () => {},
					destroy: () => {},
					render: async () => {
						await renderCaptcha();
					},
					getResponse: () => "",
					getComponentState: () => state(),
				} as THandle;
			}

			return {
				...base,
				destroy: () => {
					base.destroy();
					performCleanup();
					batch(() => {
						setState({ loading: false, error: null, ready: false });
					});
				},
				render: async () => {
					await renderCaptcha();
				},
				getComponentState: () => state(),
			} as THandle;
		});

		createEffect(() => {
			const currentHandle = handle();
			const controller = props.controller;

			if (controller) {
				controller.set(currentHandle);
			}

			if (currentHandle) {
				props.onReady?.(currentHandle);
			}
		});

		const elementId = createMemo(() => {
			const id = widgetId();
			return id !== null && id !== undefined ? `better-captcha-${id}` : "better-captcha-loading";
		});

		return (
			<div
				{...divProps}
				id={elementId()}
				ref={setElementRef}
				class={props.class}
				style={props.style}
				aria-live="polite"
				aria-busy={state().loading}
			/>
		);
	};
}

// packages/svelte/src/base-captcha.svelte
<script module lang="ts">
	import type { CaptchaHandle, Provider, ProviderConfig } from "@better-captcha/core";

	export type BaseCaptchaProps<
		TOptions,
		THandle extends CaptchaHandle,
		TProvider extends Provider<ProviderConfig, TOptions, THandle>,
	> = {
		providerClass: new (sitekeyOrEndpoint: string) => TProvider;
		sitekey?: string;
		endpoint?: string;
		options?: TOptions;
		class?: string;
		style?: string;
		autoRender?: boolean;
		onready?: (handle: THandle) => void;
		onerror?: (error: Error) => void;
	};
</script>

<script lang="ts" generics="TOptions, THandle extends CaptchaHandle, TProvider extends Provider<ProviderConfig, TOptions, THandle>">
	import type { CaptchaState, WidgetId } from "@better-captcha/core";
	import { cleanup as cleanupWidget } from "@better-captcha/core/utils/lifecycle";
	import { onMount, onDestroy } from "svelte";

	type Props = BaseCaptchaProps<TOptions, THandle, TProvider>;

	let {
		providerClass: ProviderClass,
		sitekey,
		endpoint,
		options = undefined,
		class: className = undefined,
		style = undefined,
		autoRender = true,
		onready = undefined,
		onerror = undefined
	}: Props = $props();

	let elementRef: HTMLDivElement | undefined = $state();
	let captchaState = $state<CaptchaState>({ loading: autoRender, error: null, ready: false });
	let widgetId: WidgetId | null = $state(null);

	let container: HTMLDivElement | null = null;
	let provider: TProvider | null = null;
	let isRendering = false;
let pendingRender = false;

	function cleanup(): void {
		cleanupWidget(provider, widgetId, container);
		container = null;
		provider = null;
		widgetId = null;
	}

	async function renderCaptcha(): Promise<void> {
		const host = elementRef;
	if (!host) return;

	if (isRendering) {
		pendingRender = true;
		return;
	}

		isRendering = true;
	pendingRender = false;
		cleanup();
		captchaState = { loading: true, error: null, ready: false };

		try {
			const value = endpoint ?? sitekey;
			if (!value) {
				throw new Error("Either 'sitekey' or 'endpoint' prop must be provided");
			}
			const newProvider = new ProviderClass(value);
			await newProvider.init();

			const newContainer = document.createElement("div");
			host.appendChild(newContainer);

			const id = options !== undefined
				? await newProvider.render(newContainer, options)
				: await newProvider.render(newContainer);

			if (id == null) throw new Error("Captcha render returned null widget id");

			provider = newProvider;
			container = newContainer;
			widgetId = id;
			captchaState = { loading: false, error: null, ready: true };
			hasRendered = true;
			if (onready && provider) {
				const handle = provider.getHandle(id);
				onready(handle);
			}
		} catch (error) {
			const err = error instanceof Error ? error : new Error(String(error));
			console.error("[better-captcha] render:", err);
			captchaState = { loading: false, error: err, ready: false };
			onerror?.(err);
		} finally {
			isRendering = false;
		if (pendingRender) {
			pendingRender = false;
			queueMicrotask(() => {
				void renderCaptcha();
			});
		}
		}
	}

	export async function execute(): Promise<void> {
		if (provider && widgetId != null) {
			await provider.getHandle(widgetId).execute();
		}
	}

	export function reset(): void {
		if (provider && widgetId != null) {
			provider.getHandle(widgetId).reset();
		}
	}

	export function destroy(): void {
		if (provider && widgetId != null) {
			provider.getHandle(widgetId).destroy();
		}
		cleanup();
		captchaState = { loading: false, error: null, ready: false };
	}

	export function getResponse(): string {
		if (provider && widgetId != null) {
			return provider.getHandle(widgetId).getResponse();
		}
		return "";
	}

	export function getComponentState(): CaptchaState {
		return captchaState;
	}

	export async function render(): Promise<void> {
		await renderCaptcha();
	}

	let hasRendered = false;

	onMount(() => {
		if (autoRender) {
			renderCaptcha();
		}
	});

	$effect(() => {
		sitekey;
		endpoint;
		options;
		if (autoRender && hasRendered) {
			renderCaptcha();
		}
	});

	onDestroy(() => {
		cleanup();
	});

	const elementId = $derived(
		widgetId !== null && widgetId !== undefined ? `better-captcha-${widgetId}` : "better-captcha-loading"
	);
</script>

<div
	bind:this={elementRef}
	id={elementId}
	class={className}
	{style}
	aria-live="polite"
	aria-busy={captchaState.loading}
></div>
