// packages/qwik/src/base-captcha.tsx
import type { CaptchaHandle, CaptchaState, Provider, ProviderConfig, WidgetId } from "@better-captcha/core";
import { cleanup } from "@better-captcha/core/utils/lifecycle";
import type { NoSerialize, QRL } from "@builder.io/qwik";
import { $, component$, noSerialize, useComputed$, useSignal, useTask$, useVisibleTask$ } from "@builder.io/qwik";
import type { CaptchaProps } from "./index";

export function createCaptchaComponent<
	TOptions = unknown,
	THandle extends CaptchaHandle = CaptchaHandle,
	TProvider extends Provider<ProviderConfig, TOptions, THandle> = Provider<ProviderConfig, TOptions, THandle>,
>(providerFactory$: QRL<(identifier: string) => TProvider>) {
	return component$<CaptchaProps<TOptions, THandle>>((props) => {
		const hostEl = useSignal<HTMLDivElement | null>(null);
		const provider = useSignal<TProvider | null>(null);
		const widgetId = useSignal<WidgetId | null>(null);
		const containerEl = useSignal<HTMLDivElement | null>(null);
		const state = useSignal<CaptchaState>({ loading: true, error: null, ready: false });
		const isRendering = useSignal(false);

	const identifier = useComputed$(() => (props as any).sitekey || (props as any).endpoint);

		const cleanup$ = $(() => {
			cleanup(provider.value, widgetId.value, containerEl.value);
			containerEl.value = null;
			widgetId.value = null;
			provider.value = null;
		});

		const renderCaptcha$ = $(async () => {
			const el = hostEl.value;
			if (!el || isRendering.value) return;

			isRendering.value = true;
			await cleanup$();
			state.value = { loading: true, error: null, ready: false };
			try {
				const currentValue = identifier.value;
				if (!currentValue) {
					throw new Error("Either 'sitekey' or 'endpoint' prop must be provided");
				}
				const newProvider = await providerFactory$(currentValue);
				await newProvider.init();

				const container = document.createElement("div");
				el.appendChild(container);
				containerEl.value = container;

				const id = await newProvider.render(container, props.options);
				if (id == null) throw new Error("Captcha render returned null widget id");

				provider.value = newProvider;
				widgetId.value = id;
				state.value = { loading: false, error: null, ready: true };
			} catch (err) {
				const error = err instanceof Error ? err : new Error(String(err));
				console.error("[better-captcha] render:", error);
				state.value = { loading: false, error, ready: false };
				if (props.onError) await props.onError(error);
			} finally {
				isRendering.value = false;
			}
		});

		const buildHandle$ = $((): NoSerialize<THandle> => {
			const p = provider.value;
			const id = widgetId.value;

			if (!p || id == null) {
				return noSerialize({
					execute: async () => {},
					reset: () => {},
					destroy: () => {},
					render: async () => {
						await renderCaptcha$();
					},
					getResponse: () => "",
					getComponentState: () => state.value,
				} as THandle);
			}

			const base = p.getHandle(id) as THandle;
			return noSerialize({
				...base,
				destroy: () => {
					base.destroy();
					cleanup(provider.value, widgetId.value, containerEl.value);
					containerEl.value = null;
					widgetId.value = null;
					provider.value = null;
					state.value = { loading: false, error: null, ready: false };
				},
				render: async () => {
					await renderCaptcha$();
				},
				getComponentState: () => state.value,
			} as THandle);
		});

	useVisibleTask$(async ({ track, cleanup }) => {
		track(() => hostEl.value);
		track(() => identifier.value);
		track(() => props.options);

		if (!hostEl.value) return;
		if (!identifier.value) return;

			if (props.autoRender ?? true) {
				await renderCaptcha$();
			}

			cleanup(async () => {
				await cleanup$();
			});
		});

		useTask$(async ({ track }) => {
			track(() => provider.value);
			track(() => widgetId.value);
			track(() => state.value.ready);

			if (!props.controller) return;

			props.controller.value = await buildHandle$();
		});

		useTask$(async ({ track }) => {
			track(() => state.value.ready);
			if (state.value.ready && props.onReady) {
				const handle = await buildHandle$();
				await props.onReady(handle);
			}
		});

		const elementId = useComputed$(() =>
			widgetId.value != null ? `better-captcha-${widgetId.value}` : "better-captcha-loading",
		);

		return (
			<div
				id={elementId.value}
				ref={(el: HTMLDivElement | null) => {
					hostEl.value = el;
				}}
				class={props.class}
				style={props.style}
				aria-live="polite"
				aria-busy={state.value.loading}
			/>
		);
	});
}

// packages/svelte/src/base-captcha.svelte
<script module lang="ts">
	import type { CaptchaHandle, Provider, ProviderConfig } from "@better-captcha/core";

	export type BaseCaptchaProps<
		TOptions,
		THandle extends CaptchaHandle,
		TProvider extends Provider<ProviderConfig, TOptions, THandle>,
	> = {
		providerClass: new (sitekeyOrEndpoint: string) => TProvider;
		sitekey?: string;
		endpoint?: string;
		options?: TOptions;
		class?: string;
		style?: string;
		autoRender?: boolean;
		onready?: (handle: THandle) => void;
		onerror?: (error: Error) => void;
	};
</script>

<script lang="ts" generics="TOptions, THandle extends CaptchaHandle, TProvider extends Provider<ProviderConfig, TOptions, THandle>">
	import type { CaptchaState, WidgetId } from "@better-captcha/core";
	import { cleanup as cleanupWidget } from "@better-captcha/core/utils/lifecycle";
	import { onMount, onDestroy } from "svelte";

	type Props = BaseCaptchaProps<TOptions, THandle, TProvider>;

	let {
		providerClass: ProviderClass,
		sitekey,
		endpoint,
		options = undefined,
		class: className = undefined,
		style = undefined,
		autoRender = true,
		onready = undefined,
		onerror = undefined
	}: Props = $props();

	let elementRef: HTMLDivElement | undefined = $state();
	let captchaState = $state<CaptchaState>({ loading: autoRender, error: null, ready: false });
	let widgetId: WidgetId | null = $state(null);

	let container: HTMLDivElement | null = null;
	let provider: TProvider | null = null;
	let isRendering = false;
let pendingRender = false;

	function cleanup(): void {
		cleanupWidget(provider, widgetId, container);
		container = null;
		provider = null;
		widgetId = null;
	}

	async function renderCaptcha(): Promise<void> {
		const host = elementRef;
	if (!host) return;

	if (isRendering) {
		pendingRender = true;
		return;
	}

		isRendering = true;
	pendingRender = false;
		cleanup();
		captchaState = { loading: true, error: null, ready: false };

		try {
			const value = endpoint ?? sitekey;
			if (!value) {
				throw new Error("Either 'sitekey' or 'endpoint' prop must be provided");
			}
			const newProvider = new ProviderClass(value);
			await newProvider.init();

			const newContainer = document.createElement("div");
			host.appendChild(newContainer);

			const id = options !== undefined
				? await newProvider.render(newContainer, options)
				: await newProvider.render(newContainer);

			if (id == null) throw new Error("Captcha render returned null widget id");

			provider = newProvider;
			container = newContainer;
			widgetId = id;
			captchaState = { loading: false, error: null, ready: true };
			hasRendered = true;
			if (onready && provider) {
				const handle = provider.getHandle(id);
				onready(handle);
			}
		} catch (error) {
			const err = error instanceof Error ? error : new Error(String(error));
			console.error("[better-captcha] render:", err);
			captchaState = { loading: false, error: err, ready: false };
			onerror?.(err);
		} finally {
			isRendering = false;
		if (pendingRender) {
			pendingRender = false;
			queueMicrotask(() => {
				void renderCaptcha();
			});
		}
		}
	}

	export async function execute(): Promise<void> {
		if (provider && widgetId != null) {
			await provider.getHandle(widgetId).execute();
		}
	}

	export function reset(): void {
		if (provider && widgetId != null) {
			provider.getHandle(widgetId).reset();
		}
	}

	export function destroy(): void {
		if (provider && widgetId != null) {
			provider.getHandle(widgetId).destroy();
		}
		cleanup();
		captchaState = { loading: false, error: null, ready: false };
	}

	export function getResponse(): string {
		if (provider && widgetId != null) {
			return provider.getHandle(widgetId).getResponse();
		}
		return "";
	}

	export function getComponentState(): CaptchaState {
		return captchaState;
	}

	export async function render(): Promise<void> {
		await renderCaptcha();
	}

	let hasRendered = false;

	onMount(() => {
		if (autoRender) {
			renderCaptcha();
		}
	});

	$effect(() => {
		sitekey;
		endpoint;
		options;
		if (autoRender && hasRendered) {
			renderCaptcha();
		}
	});

	onDestroy(() => {
		cleanup();
	});

	const elementId = $derived(
		widgetId !== null && widgetId !== undefined ? `better-captcha-${widgetId}` : "better-captcha-loading"
	);
</script>

<div
	bind:this={elementRef}
	id={elementId}
	class={className}
	{style}
	aria-live="polite"
	aria-busy={captchaState.loading}
></div>
