// packages/react/src/base-captcha.tsx
"use client";

import type { CaptchaHandle, Provider, ProviderConfig } from "@better-captcha/core";
import { forwardRef, useImperativeHandle, useMemo } from "react";
import type { CaptchaProps, CaptchaPropsWithEndpoint } from "./index";
import { useCaptchaLifecycle } from "./use-captcha-lifecycle";

const defaultHandle: CaptchaHandle = {
	execute: async () => {},
	reset: () => {},
	destroy: () => {},
	render: async () => {},
	getResponse: () => "",
	getComponentState: () => ({
		loading: false,
		error: null,
		ready: false,
	}),
};

type ValueProp = "sitekey" | "endpoint";

type PropsForValue<TOptions, TValue extends ValueProp> = TValue extends "sitekey"
	? CaptchaProps<TOptions>
	: CaptchaPropsWithEndpoint<TOptions>;

function createComponentInternal<
	TOptions = unknown,
	THandle extends CaptchaHandle = CaptchaHandle,
	TValue extends ValueProp = "sitekey",
>(
	ProviderClass: new (sitekeyOrEndpoint: string) => Provider<ProviderConfig, TOptions, THandle>,
	valueProp: TValue,
	errorMessage: string,
) {
	return forwardRef<THandle, PropsForValue<TOptions, TValue>>(function CaptchaComponent(props, ref) {
		const { options, className, style, autoRender = true } = props;
		const value = props[valueProp];
		if (!value) {
			throw new Error(errorMessage);
		}

		const provider = useMemo(() => new ProviderClass(value as string), [ProviderClass, value]);
		const { elementRef, state, widgetIdRef, setState, renderCaptcha } = useCaptchaLifecycle(
			provider,
			options,
			autoRender,
		);

		useImperativeHandle(ref, () => {
			const id = widgetIdRef.current;
			const handle = id != null ? provider.getHandle(id) : (defaultHandle as THandle);

			return {
				...handle,
				getComponentState: () => state,
				destroy: () => {
					if (id != null) {
						handle.destroy();
						widgetIdRef.current = null;
						setState((prev) => ({ ...prev, ready: false, error: null }));
					}
				},
				render: async () => {
					await renderCaptcha();
				},
			};
		}, [provider, state, widgetIdRef, setState, renderCaptcha]);

		const widgetId = widgetIdRef.current;
		const elementId =
			widgetId !== null && widgetId !== undefined ? `better-captcha-${widgetId}` : "better-captcha-loading";

		return (
			<div
				id={elementId}
				ref={elementRef}
				className={className}
				style={style}
				aria-live="polite"
				aria-busy={state.loading}
			/>
		);
	});
}

export function createCaptchaComponent<TOptions = unknown, THandle extends CaptchaHandle = CaptchaHandle>(
	ProviderClass: new (sitekeyOrEndpoint: string) => Provider<ProviderConfig, TOptions, THandle>,
) {
	return createComponentInternal<TOptions, THandle, "sitekey">(
		ProviderClass,
		"sitekey",
		"'sitekey' prop must be provided",
	);
}

export function createCaptchaComponentWithEndpoint<TOptions = unknown, THandle extends CaptchaHandle = CaptchaHandle>(
	ProviderClass: new (sitekeyOrEndpoint: string) => Provider<ProviderConfig, TOptions, THandle>,
) {
	return createComponentInternal<TOptions, THandle, "endpoint">(
		ProviderClass,
		"endpoint",
		"'endpoint' prop must be provided",
	);
}

// packages/qwik/src/base-captcha.tsx
import type { CaptchaHandle, CaptchaState, Provider, ProviderConfig, WidgetId } from "@better-captcha/core";
import { cleanup } from "@better-captcha/core/utils/lifecycle";
import type { NoSerialize, QRL, Signal } from "@builder.io/qwik";
import { $, component$, noSerialize, useComputed$, useSignal, useTask$, useVisibleTask$ } from "@builder.io/qwik";
import type { CaptchaProps, CaptchaPropsWithEndpoint } from "./index";

type ValueProp = "sitekey" | "endpoint";

type PropsForValue<TOptions, THandle extends CaptchaHandle, TValue extends ValueProp> = TValue extends "sitekey"
	? CaptchaProps<TOptions, THandle>
	: CaptchaPropsWithEndpoint<TOptions, THandle>;

function createComponentInternal<
	TOptions = unknown,
	THandle extends CaptchaHandle = CaptchaHandle,
	TProvider extends Provider<ProviderConfig, TOptions, THandle> = Provider<ProviderConfig, TOptions, THandle>,
>(providerFactory$: QRL<(sitekeyOrEndpoint: string) => TProvider>, valueProp: ValueProp, errorMessage: string) {
	return component$<PropsForValue<TOptions, THandle, typeof valueProp>>((props) => {
		const hostEl = useSignal<HTMLDivElement | null>(null);
		const provider = useSignal<TProvider | null>(null);
		const widgetId = useSignal<WidgetId | null>(null);
		const containerEl = useSignal<HTMLDivElement | null>(null);
		const state = useSignal<CaptchaState>({ loading: true, error: null, ready: false });
		const isRendering = useSignal(false);

		const cleanup$ = $(() => {
			cleanup(provider.value, widgetId.value, containerEl.value);
			containerEl.value = null;
			widgetId.value = null;
			provider.value = null;
		});

		const renderCaptcha$ = $(async () => {
			const el = hostEl.value;
			if (!el || isRendering.value) return;

			isRendering.value = true;
			await cleanup$();
			state.value = { loading: true, error: null, ready: false };

			try {
				const value = props[valueProp];
				if (!value) {
					throw new Error(errorMessage);
				}
				const newProvider = await providerFactory$(value as string);
				await newProvider.init();

				const container = document.createElement("div");
				el.appendChild(container);
				containerEl.value = container;

				const id = await newProvider.render(container, props.options);
				if (id == null) throw new Error("Captcha render returned null widget id");

				provider.value = newProvider;
				widgetId.value = id;
				state.value = { loading: false, error: null, ready: true };
			} catch (err) {
				const error = err instanceof Error ? err : new Error(String(err));
				console.error("[better-captcha] render:", error);
				state.value = { loading: false, error, ready: false };
				if (props.onError) await props.onError(error);
			} finally {
				isRendering.value = false;
			}
		});

		const buildHandle$ = $((): NoSerialize<THandle> => {
			const p = provider.value;
			const id = widgetId.value;

			if (!p || id == null) {
				return noSerialize({
					execute: async () => {},
					reset: () => {},
					destroy: () => {},
					render: async () => {
						await renderCaptcha$();
					},
					getResponse: () => "",
					getComponentState: () => state.value,
				} as THandle);
			}

			const base = p.getHandle(id) as THandle;
			return noSerialize({
				...base,
				destroy: () => {
					base.destroy();
					cleanup(provider.value, widgetId.value, containerEl.value);
					containerEl.value = null;
					widgetId.value = null;
					provider.value = null;
					state.value = { loading: false, error: null, ready: false };
				},
				render: async () => {
					await renderCaptcha$();
				},
				getComponentState: () => state.value,
			} as THandle);
		});

		useVisibleTask$(async ({ track, cleanup }) => {
			track(() => hostEl.value);
			track(() => props[valueProp]);
			track(() => props.options);

			if (!hostEl.value) return;
			const value = props[valueProp];
			if (!value) return;

			if (props.autoRender ?? true) {
				await renderCaptcha$();
			}

			cleanup(async () => {
				await cleanup$();
			});
		});

		useTask$(async ({ track }) => {
			track(() => provider.value);
			track(() => widgetId.value);
			track(() => state.value.ready);

			if (!props.controller) return;

			props.controller.value = await buildHandle$();
		});

		useTask$(async ({ track }) => {
			track(() => state.value.ready);
			if (state.value.ready && props.onReady) {
				const handle = await buildHandle$();
				await props.onReady(handle);
			}
		});

		const elementId = useComputed$(() =>
			widgetId.value != null ? `better-captcha-${widgetId.value}` : "better-captcha-loading",
		);

		return (
			<div
				id={elementId.value}
				ref={(el: HTMLDivElement | null) => {
					hostEl.value = el;
				}}
				class={props.class}
				style={props.style}
				aria-live="polite"
				aria-busy={state.value.loading}
			/>
		);
	});
}

export function createCaptchaComponent<
	TOptions = unknown,
	THandle extends CaptchaHandle = CaptchaHandle,
	TProvider extends Provider<ProviderConfig, TOptions, THandle> = Provider<ProviderConfig, TOptions, THandle>,
>(providerFactory$: QRL<(sitekeyOrEndpoint: string) => TProvider>) {
	return createComponentInternal<TOptions, THandle, TProvider>(
		providerFactory$,
		"sitekey",
		"'sitekey' prop must be provided",
	);
}

export function createCaptchaComponentWithEndpoint<
	TOptions = unknown,
	THandle extends CaptchaHandle = CaptchaHandle,
	TProvider extends Provider<ProviderConfig, TOptions, THandle> = Provider<ProviderConfig, TOptions, THandle>,
>(providerFactory$: QRL<(sitekeyOrEndpoint: string) => TProvider>) {
	return createComponentInternal<TOptions, THandle, TProvider>(
		providerFactory$,
		"endpoint",
		"'endpoint' prop must be provided",
	);
}
