// apps/testing/svelte/src/components/CaptchaFoxTest.svelte
<script lang="ts">
	import type { CaptchaFoxHandle, RenderParameters } from "@better-captcha/svelte/provider/captcha-fox";
	import CaptchaFox from "@better-captcha/svelte/provider/captcha-fox";
	import { writable } from "svelte/store";
	import RenderCaptcha, { type CaptchaComponentMode } from "./render-captcha.svelte";

	let { mode }: { mode: CaptchaComponentMode } = $props();

	let captchaRef: RenderCaptcha | undefined;
	const response = writable<string | null>(null);
	const error = writable<Error | null>(null);
	const solved = writable<boolean>(false);

	let options = $state<Omit<RenderParameters, "sitekey">>({
		theme: "light",
		mode: "inline",
	});

	function onReady(handle: CaptchaFoxHandle) {
		console.log("Captcha ready!", handle);
	}

	function onError(err: Error) {
		error.set(err);
		console.error("Captcha error:", err);
	}

	function onSolve(token: string) {
		solved.set(true);
		console.log("Captcha solved with token:", token);
	}

	function handleDestroy() {
		captchaRef?.destroy();
	}

	function handleReset() {
		captchaRef?.reset();
		response.set(null);
	}

	async function handleExecute() {
		await captchaRef?.execute();
	}

	async function handleRender() {
		await captchaRef?.render();
	}

	function handleGetResponse() {
		const captchaResponse = captchaRef?.getResponse() || "No response";
		response.set(captchaResponse);
	}

	function handleChangeTheme() {
		const themes = ["light", "dark"] as const;
		const currentTheme = options.theme;
		const normalizedTheme =
			!currentTheme || typeof currentTheme !== "string" || currentTheme === "auto" ? "light" : currentTheme;
		const currentIndex = themes.indexOf(normalizedTheme as "light" | "dark");
		const nextIndex = (currentIndex + 1) % themes.length;
		options = { ...options, theme: themes[nextIndex] };
	}
</script>

<div>
	<h3>Captcha Fox Test</h3>
	<RenderCaptcha
		{mode}
		provider="captcha-fox"
		component={CaptchaFox}
		bind:this={captchaRef}
		sitekey="sk_11111111000000001111111100000000"
		{options}
		onready={onReady}
		onerror={onError}
		onSolve={onSolve}
	/>
	{#if $solved}
		<p id="captcha-solved">Captcha Solved!</p>
	{/if}
	<div style="margin-top: 10px">
		<button type="button" onclick={handleDestroy}>Destroy</button>
		<button type="button" onclick={handleReset}>Reset</button>
		<button type="button" onclick={handleExecute}>Execute</button>
		<button type="button" onclick={handleRender}>Render</button>
		<button type="button" onclick={handleGetResponse}>Get Response</button>
		<button type="button" onclick={handleChangeTheme}>Change Theme</button>
	</div>
	{#if $response}
		<p id="captcha-response">{$response}</p>
	{/if}
	{#if $error}
		<p style="color: red">Error: {$error.message}</p>
	{/if}
</div>

// apps/testing/vue/src/components/CaptchaFoxTest.vue
<template>
	<div>
		<h3>Captcha Fox Test</h3>
		<RenderCaptcha :mode="mode" provider="captcha-fox" :component="CaptchaFox"
			ref="captchaRef"
			sitekey="sk_11111111000000001111111100000000"
			:options="options"
			@ready="onReady"
			@error="onError"
			@solve="onSolve"
		/>
		<p v-if="solved" id="captcha-solved">Captcha Solved!</p>
		<div style="margin-top: 10px">
			<button type="button" @click="handleDestroy">Destroy</button>
			<button type="button" @click="handleReset">Reset</button>
			<button type="button" @click="handleExecute">Execute</button>
			<button type="button" @click="handleRender">Render</button>
			<button type="button" @click="handleGetResponse">Get Response</button>
			<button type="button" @click="handleChangeTheme">Change Theme</button>
		</div>
		<p v-if="response" id="captcha-response">{{ response }}</p>
		<p v-if="error" style="color: red">Error: {{ error.message }}</p>
	</div>
</template>

<script setup lang="ts">
	import { CaptchaFox, type CaptchaFoxHandle, type RenderParameters } from "@better-captcha/vue/provider/captcha-fox";
	import { ref } from "vue";
	import RenderCaptcha, { type CaptchaComponentMode } from "./RenderCaptcha.vue";
	defineProps<{ mode: CaptchaComponentMode }>();

	const captchaRef = ref<CaptchaFoxHandle | null>(null);
	const response = ref<string | null>(null);
	const error = ref<Error | null>(null);
	const solved = ref<boolean>(false);

	const options = ref<Omit<RenderParameters, "element" | "sitekey">>({
		lang: "en",
		theme: "light",
	});

	const onReady = (handle: CaptchaFoxHandle) => {
		console.log("Captcha ready!", handle);
	};

	const onError = (err: Error) => {
		error.value = err;
		console.error("Captcha error:", err);
	};

	const onSolve = (token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	};

	const handleDestroy = () => {
		captchaRef.value?.destroy();
	};

	const handleReset = () => {
		captchaRef.value?.reset();
		response.value = null;
	};

	const handleExecute = async () => {
		await captchaRef.value?.execute();
	};

	const handleRender = async () => {
		await captchaRef.value?.render();
	};

	const handleGetResponse = () => {
		const captchaResponse = captchaRef.value?.getResponse() || "No response";
		response.value = captchaResponse;
	};

	const handleChangeTheme = () => {
		const themes = ["light", "dark"] as const;
		const currentTheme =
			options.value.theme === "light" || options.value.theme === "dark" ? options.value.theme : "light";
		const currentIndex = themes.indexOf(currentTheme);
		const nextIndex = (currentIndex + 1) % themes.length;
		options.value = { ...options.value, theme: themes[nextIndex] };
	};
</script>
