// apps/testing/svelte/src/components/RecaptchaTest.svelte
<script lang="ts">
	import ReCaptcha from "@better-captcha/svelte/provider/recaptcha";
	import type { ReCaptchaHandle, RenderParameters } from "@better-captcha/svelte/provider/recaptcha";
	import { writable } from "svelte/store";

	let captchaRef: ReCaptcha | undefined;
	const response = writable<string | null>(null);
	const error = writable<Error | null>(null);

	let options = $state<Omit<RenderParameters, "sitekey">>({
		theme: "light",
		size: "normal",
	});

	function onReady(handle: ReCaptchaHandle) {
		console.log("Captcha ready!", handle);
	}

	function onError(err: Error) {
		error.set(err);
		console.error("Captcha error:", err);
	}

	function handleDestroy() {
		captchaRef?.destroy();
	}

	function handleReset() {
		captchaRef?.reset();
		response.set(null);
	}

	async function handleExecute() {
		await captchaRef?.execute();
	}

	function handleGetResponse() {
		const captchaResponse = captchaRef?.getResponse() || "No response";
		response.set(captchaResponse);
	}

	function handleChangeTheme() {
		const themes = ["light", "dark"] as const;
		const currentIndex = themes.indexOf(options.theme || "light");
		const nextIndex = (currentIndex + 1) % themes.length;
		options = { ...options, theme: themes[nextIndex] };
	}
</script>

<div>
	<h3>reCAPTCHA Test</h3>
	<ReCaptcha
		bind:this={captchaRef}
		sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
		{options}
		onready={onReady}
		onerror={onError}
	/>
	<div style="margin-top: 10px">
		<button type="button" onclick={handleDestroy}>Destroy</button>
		<button type="button" onclick={handleReset}>Reset</button>
		<button type="button" onclick={handleExecute}>Execute</button>
		<button type="button" onclick={handleGetResponse}>Get Response</button>
		<button type="button" onclick={handleChangeTheme}>Change Theme</button>
	</div>
	{#if $response}
		<p id="captcha-response">{$response}</p>
	{/if}
	{#if $error}
		<p style="color: red">Error: {$error.message}</p>
	{/if}
</div>

// apps/testing/vue/src/components/RecaptchaTest.vue
<template>
	<div>
		<h3>reCAPTCHA Test</h3>
		<ReCaptcha
			ref="captchaRef"
			sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
			:options="options"
			@ready="onReady"
			@error="onError"
		/>
		<div style="margin-top: 10px">
			<button type="button" @click="handleDestroy">Destroy</button>
			<button type="button" @click="handleReset">Reset</button>
			<button type="button" @click="handleExecute">Execute</button>
			<button type="button" @click="handleGetResponse">Get Response</button>
			<button type="button" @click="handleChangeTheme">Change Theme</button>
		</div>
		<p v-if="response" id="captcha-response">{{ response }}</p>
		<p v-if="error" style="color: red">Error: {{ error.message }}</p>
	</div>
</template>

<script setup lang="ts">
	import { ReCaptcha, type ReCaptchaHandle, type RenderParameters } from "@better-captcha/vue/provider/recaptcha";
	import { ref } from "vue";

	const captchaRef = ref<ReCaptchaHandle | null>(null);
	const response = ref<string | null>(null);
	const error = ref<Error | null>(null);

	const options = ref<Omit<RenderParameters, "sitekey">>({
		theme: "light",
		size: "normal",
	});

	const onReady = (handle: ReCaptchaHandle) => {
		console.log("Captcha ready!", handle);
	};

	const onError = (err: Error) => {
		error.value = err;
		console.error("Captcha error:", err);
	};

	const handleDestroy = () => {
		captchaRef.value?.destroy();
	};

	const handleReset = () => {
		captchaRef.value?.reset();
		response.value = null;
	};

	const handleExecute = async () => {
		await captchaRef.value?.execute();
	};

	const handleGetResponse = () => {
		const captchaResponse = captchaRef.value?.getResponse() || "No response";
		response.value = captchaResponse;
	};

	const handleChangeTheme = () => {
		const themes = ["light", "dark"] as const;
		const currentIndex = themes.indexOf(options.value.theme || "light");
		const nextIndex = (currentIndex + 1) % themes.length;
		options.value = { ...options.value, theme: themes[nextIndex] };
	};
</script>
