// apps/testing/lit/src/tsec-test.ts
import { TSec, type TSecHandle } from "@better-captcha/lit/provider/t-sec";
import { html, LitElement } from "lit";
import { customElement, state } from "lit/decorators.js";
import { createRef, type Ref, ref } from "lit/directives/ref.js";

TSec;

type TSecCaptchaElement = LitElement & { getHandle: () => TSecHandle };

@customElement("tsec-test")
export class TSecTest extends LitElement {
	private captchaRef: Ref<TSecCaptchaElement> = createRef();

	@state()
	private response: ReturnType<TSecHandle["getResponse"]> = null;

	@state()
	private solved = false;

	protected createRenderRoot() {
		return this;
	}

	private handleSolve = (token: string) => {
		this.solved = true;
		console.log("Captcha solved with token:", token);
	};

	private handleDestroy() {
		this.captchaRef.value?.getHandle()?.destroy();
	}

	private handleReset() {
		this.captchaRef.value?.getHandle()?.reset();
	}

	private handleExecute() {
		this.captchaRef.value?.getHandle()?.execute();
	}

	private async handleRender() {
		await this.captchaRef.value?.getHandle()?.render();
	}

	private handleGetResponse() {
		const captchaResponse = this.captchaRef.value?.getHandle()?.getResponse() ?? null;
		this.response = captchaResponse;
	}

	render() {
		return html`
			<div>
				<t-sec-captcha
					${ref(this.captchaRef)}
					sitekey="189910271"
					.options=${{ userLanguage: "en" }}
					.onSolve=${this.handleSolve}
				></t-sec-captcha>
				${this.solved ? html`<p id="captcha-solved">Captcha Solved!</p>` : ""}
				<button type="button" @click=${this.handleDestroy}>Destroy</button>
				<button type="button" @click=${this.handleReset}>Reset</button>
				<button type="button" @click=${this.handleExecute}>Execute</button>
				<button type="button" @click=${this.handleRender}>Render</button>
				<button type="button" @click=${this.handleGetResponse}>Get Response</button>
				${this.response ? html`<p id="captcha-response">${JSON.stringify(this.response, null, "\t")}</p>` : ""}
			</div>
		`;
	}
}

declare global {
	interface HTMLElementTagNameMap {
		"tsec-test": TSecTest;
	}
}

// apps/testing/vue/src/components/TSecTest.vue
<template>
	<div>
		<h3>T-Sec Test</h3>
		<TSec ref="captchaRef" sitekey="189910271" :options="options" @ready="onReady" @error="onError" @solve="onSolve" />
		<p v-if="solved" id="captcha-solved">Captcha Solved!</p>
		<div style="margin-top: 10px">
			<button type="button" @click="handleDestroy">Destroy</button>
			<button type="button" @click="handleReset">Reset</button>
			<button type="button" @click="handleExecute">Execute</button>
			<button type="button" @click="handleRender">Render</button>
			<button type="button" @click="handleGetResponse">Get Response</button>
		</div>
		<p v-if="response" id="captcha-response">{{ JSON.stringify(response, null, "\t") }}</p>
		<p v-if="error" style="color: red">Error: {{ error.message }}</p>
	</div>
</template>

<script setup lang="ts">
import { TSec, type TSecHandle, type RenderParameters} from "@better-captcha/vue/provider/t-sec";
	import { ref } from "vue";

	const captchaRef = ref<TSecHandle | null>(null);
	const response = ref<ReturnType<TSecHandle["getResponse"]>>(null);
	const error = ref<Error | null>(null);
	const solved = ref<boolean>(false);

  const options = ref<RenderParameters>({
    userLanguage: "en",
  });

	const onReady = (handle: TSecHandle) => {
		console.log("Captcha ready!", handle);
	};

	const onError = (err: Error) => {
		error.value = err;
		console.error("Captcha error:", err);
	};

	const onSolve = (token: ReturnType<TSecHandle['getResponse']>) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	};

	const handleDestroy = () => {
		captchaRef.value?.destroy();
	};

	const handleReset = () => {
		captchaRef.value?.reset();
		response.value = null;
	};

	const handleExecute = async () => {
		await captchaRef.value?.execute();
	};

	const handleRender = async () => {
		await captchaRef.value?.render();
	};

	const handleGetResponse = () => {
		const captchaResponse = captchaRef.value?.getResponse() ?? null;
		response.value = captchaResponse;
	};
</script>
