// apps/testing/react/src/tsec-test.tsx
import { TSec, type TSecHandle } from "@better-captcha/react/provider/t-sec";
import { useRef, useState } from "react";
import { RenderCaptcha, type CaptchaComponentMode } from "./render-captcha";

export function TSecTest({ mode }: { mode: CaptchaComponentMode }) {
	const tsecRef = useRef<TSecHandle>(null);
	const [response, setResponse] = useState<ReturnType<TSecHandle['getResponse']>>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = tsecRef.current?.getResponse() ?? null;
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha mode={mode} provider="t-sec" component={TSec}
				ref={tsecRef}
				sitekey="189910271"
				onSolve={handleSolve}
				options={{ userLanguage: "en" }}
			/>
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => tsecRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => tsecRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => tsecRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => tsecRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			{response && <p id="captcha-response">{JSON.stringify(response, null, "\t")}</p>}
		</div>
	);
}

// apps/testing/qwik/src/components/tsec-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import { TSec, type TSecHandle } from "@better-captcha/qwik/provider/t-sec";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const TSecTest = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<TSecHandle>();
	const response = useSignal<ReturnType<TSecHandle["getResponse"]>>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="t-sec"
				component={TSec}
				controller={controller}
				sitekey="189910271"
				onSolve$={handleSolve$}
				options={{ userLanguage: "en" }}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.execute();
				}}
			>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() ?? null;
					response.value = captchaResponse;
				}}
			>
				Get Response
			</button>
			{response.value && <p id="captcha-response">{JSON.stringify(response.value, null, "\t")}</p>}
		</div>
	);
});
