// apps/testing/svelte/src/App.svelte
<script lang="ts">
	import { writable } from "svelte/store";
	import AltchaTest from "./components/AltchaTest.svelte";
	import CapWidgetTest from "./components/CapWidgetTest.svelte";
	import CaptchaFoxTest from "./components/CaptchaFoxTest.svelte";
	import FriendlyCaptchaTest from "./components/FriendlyCaptchaTest.svelte";
	import HCaptchaTest from "./components/HCaptchaTest.svelte";
	import PrivateCaptchaTest from "./components/PrivateCaptchaTest.svelte";
	import ProsopoTest from "./components/ProsopoTest.svelte";
	import RecaptchaTest from "./components/RecaptchaTest.svelte";
	import RecaptchaV3Test from "./components/RecaptchaV3Test.svelte";
	import TurnstileTest from "./components/TurnstileTest.svelte";
	import GeetestTest from "./components/GeetestTest.svelte";

	const currentProvider = writable("turnstile");

	const providers = [
		{ key: "turnstile", name: "Turnstile" },
		{ key: "hcaptcha", name: "hCaptcha" },
		{ key: "recaptcha", name: "reCAPTCHA" },
		{ key: "recaptcha-v3", name: "reCAPTCHA v3" },
		{ key: "friendly-captcha", name: "Friendly Captcha" },
		{ key: "private-captcha", name: "Private Captcha" },
		{ key: "captcha-fox", name: "Captcha Fox" },
		{ key: "prosopo", name: "Prosopo" },
		{ key: "cap-widget", name: "CapWidget" },
		{ key: "altcha", name: "Altcha" },
		{ key: "geetest", name: "Geetest" },
	];

	function setProvider(key: string) {
		currentProvider.set(key);
	}
</script>

<div>
	<h1>Svelte Captcha Testing</h1>

	<div>
		<h2>Select Provider:</h2>
		{#each providers as provider}
			<button type="button" onclick={() => setProvider(provider.key)} style="margin: 5px; padding: 10px;">
				{provider.name}
			</button>
		{/each}
	</div>

	<div style="margin-top: 20px">
		{#if $currentProvider === "turnstile"}
			<TurnstileTest />
		{:else if $currentProvider === "hcaptcha"}
			<HCaptchaTest />
		{:else if $currentProvider === "recaptcha"}
			<RecaptchaTest />
		{:else if $currentProvider === "recaptcha-v3"}
			<RecaptchaV3Test />
		{:else if $currentProvider === "friendly-captcha"}
			<FriendlyCaptchaTest />
		{:else if $currentProvider === "private-captcha"}
			<PrivateCaptchaTest />
		{:else if $currentProvider === "captcha-fox"}
			<CaptchaFoxTest />
		{:else if $currentProvider === "prosopo"}
			<ProsopoTest />
		{:else if $currentProvider === "cap-widget"}
			<CapWidgetTest />
		{:else if $currentProvider === "altcha"}
			<AltchaTest />
		{:else if $currentProvider === "geetest"}
			<GeetestTest />
		{/if}
	</div>
</div>

// apps/testing/vue/src/App.vue
<template>
	<div>
		<h1>Vue Captcha Testing</h1>

		<div>
			<h2>Select Provider:</h2>
			<button
				v-for="provider in providers"
				:key="provider.key"
				type="button"
				@click="currentProvider = provider.key"
				:style="{ margin: '5px', padding: '10px' }"
			>
				{{ provider.name }}
			</button>
		</div>

		<div style="margin-top: 20px">
			<TurnstileTest v-if="currentProvider === 'turnstile'" />
			<HCaptchaTest v-else-if="currentProvider === 'hcaptcha'" />
			<RecaptchaTest v-else-if="currentProvider === 'recaptcha'" />
			<RecaptchaV3Test v-else-if="currentProvider === 'recaptcha-v3'" />
			<FriendlyCaptchaTest v-else-if="currentProvider === 'friendly-captcha'" />
			<PrivateCaptchaTest v-else-if="currentProvider === 'private-captcha'" />
			<CaptchaFoxTest v-else-if="currentProvider === 'captcha-fox'" />
			<ProsopoTest v-else-if="currentProvider === 'prosopo'" />
			<CapWidgetTest v-else-if="currentProvider === 'cap-widget'" />
			<AltchaTest v-else-if="currentProvider === 'altcha'" />
			<GeetestTest v-else-if="currentProvider === 'geetest'" />
		</div>
	</div>
</template>

<script setup lang="ts">
	import { ref } from "vue";
	import AltchaTest from "./components/AltchaTest.vue";
	import CapWidgetTest from "./components/CapWidgetTest.vue";
	import CaptchaFoxTest from "./components/CaptchaFoxTest.vue";
	import FriendlyCaptchaTest from "./components/FriendlyCaptchaTest.vue";
	import HCaptchaTest from "./components/HCaptchaTest.vue";
	import PrivateCaptchaTest from "./components/PrivateCaptchaTest.vue";
	import ProsopoTest from "./components/ProsopoTest.vue";
	import RecaptchaTest from "./components/RecaptchaTest.vue";
	import RecaptchaV3Test from "./components/RecaptchaV3Test.vue";
	import TurnstileTest from "./components/TurnstileTest.vue";
	import GeetestTest from "./components/GeetestTest.vue";

	const currentProvider = ref("turnstile");

	const providers = [
		{ key: "turnstile", name: "Turnstile" },
		{ key: "hcaptcha", name: "hCaptcha" },
		{ key: "recaptcha", name: "reCAPTCHA" },
		{ key: "recaptcha-v3", name: "reCAPTCHA v3" },
		{ key: "friendly-captcha", name: "Friendly Captcha" },
		{ key: "private-captcha", name: "Private Captcha" },
		{ key: "captcha-fox", name: "Captcha Fox" },
		{ key: "prosopo", name: "Prosopo" },
		{ key: "cap-widget", name: "CapWidget" },
		{ key: "altcha", name: "Altcha" },
		{ key: "geetest", name: "Geetest" },
	];
</script>
