// apps/testing/qwik/src/components/friendly-captcha-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import {
	FriendlyCaptcha,
	type FriendlyCaptchaHandle,
	type RenderParameters,
} from "@better-captcha/qwik/provider/friendly-captcha";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const FriendlyCaptchaTest = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<FriendlyCaptchaHandle>();
	const options = useSignal<Omit<RenderParameters, "sitekey" | "element">>({
		theme: "light",
		startMode: "focus",
	});
	const response = useSignal<string | null>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="friendly-captcha"
				component={FriendlyCaptcha}
				controller={controller}
				options={options.value}
				sitekey="FC-00000000-0000-0000-0000-000000000000"
				onSolve$={handleSolve$}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.execute();
				}}
			>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() || "No response";
					response.value = captchaResponse;
				}}
			>
				Get Response
			</button>
			<button
				type="button"
				onClick$={() => {
					const themes = ["light", "dark", "auto"];
					const currentIndex = themes.indexOf(options.value.theme || "auto");
					const nextIndex = (currentIndex + 1) % themes.length;
					options.value = { ...options.value, theme: themes[nextIndex] as RenderParameters["theme"] };
				}}
			>
				Change Theme
			</button>
			{response.value && <p id="captcha-response">{response.value}</p>}
		</div>
	);
});

// apps/testing/solidjs/src/components/friendly-captcha-test.tsx
import { createCaptchaController } from "@better-captcha/solidjs";
import {
	FriendlyCaptcha,
	type FriendlyCaptchaHandle,
	type RenderParameters,
} from "@better-captcha/solidjs/provider/friendly-captcha";
import { createSignal } from "solid-js";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export function FriendlyCaptchaTest(props: { mode: CaptchaComponentMode }) {
	const controller = createCaptchaController<FriendlyCaptchaHandle>();
	const [options, setOptions] = createSignal<Omit<RenderParameters, "sitekey" | "element">>({
		theme: "light",
		startMode: "focus",
	});
	const [response, setResponse] = createSignal<string | null>(null);
	const [solved, setSolved] = createSignal<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = controller.handle()?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha
				mode={props.mode}
				provider="friendly-captcha"
				component={FriendlyCaptcha}
				controller={controller}
				sitekey="FC-00000000-0000-0000-0000-000000000000"
				options={options()}
				onSolve={handleSolve}
			/>
			{solved() && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => controller.handle()?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => controller.handle()?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => controller.handle()?.execute()}>
				Execute
			</button>
			<button type="button" onClick={async () => await controller.handle()?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			<button
				type="button"
				onClick={() => {
					const themes = ["light", "dark", "auto"];
					const currentIndex = themes.indexOf(options().theme || "auto");
					const nextIndex = (currentIndex + 1) % themes.length;
					setOptions({ ...options(), theme: themes[nextIndex] as "light" | "dark" | "auto" });
				}}
			>
				Change Theme
			</button>
			{response() && <p id="captcha-response">{response()}</p>}
		</div>
	);
}
