// apps/testing/qwik/src/components/geetest-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import {
	Geetest,
	type GeetestHandle,
	type GeetestSolveResponse,
	type RenderParameters,
} from "@better-captcha/qwik/provider/geetest";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const GeetestTest = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<GeetestHandle>();
	const options = useSignal<RenderParameters>({
		language: "eng",
	});
	const response = useSignal<string | null>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: GeetestSolveResponse) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="geetest"
				component={Geetest}
				controller={controller}
				options={options.value}
				sitekey="647f5ed2ed8acb4be36784e01556bb71"
				onSolve$={handleSolve$}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.execute();
				}}
			>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() || "No response";
					response.value = JSON.stringify(captchaResponse, null, "\t");
				}}
			>
				Get Response
			</button>
			{response.value && <p id="captcha-response">{response.value}</p>}
		</div>
	);
});

// apps/testing/solidjs/src/components/geetest-test.tsx
import { createCaptchaController } from "@better-captcha/solidjs";
import {
	Geetest,
	type GeetestHandle,
	type GeetestSolveResponse,
	type RenderParameters,
} from "@better-captcha/solidjs/provider/geetest";
import { createSignal } from "solid-js";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export function GeetestTest(props: { mode: CaptchaComponentMode }) {
	const controller = createCaptchaController<GeetestHandle>();
	const [options, _setOptions] = createSignal<RenderParameters>({
		language: "eng",
	});
	const [response, setResponse] = createSignal<string | null>(null);
	const [solved, setSolved] = createSignal<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = controller.handle()?.getResponse() || "No response";
		setResponse(JSON.stringify(captchaResponse, null, "\t"));
	};

	const handleSolve = (token: GeetestSolveResponse) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha
				mode={props.mode}
				provider="geetest"
				component={Geetest}
				controller={controller}
				sitekey="647f5ed2ed8acb4be36784e01556bb71"
				options={options()}
				onSolve={handleSolve}
			/>
			{solved() && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => controller.handle()?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => controller.handle()?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => controller.handle()?.execute()}>
				Execute
			</button>
			<button type="button" onClick={async () => await controller.handle()?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			{response() && <p id="captcha-response">{response()}</p>}
		</div>
	);
}
