// apps/testing/qwik/src/components/prosopo-test.tsx
import { useCaptchaController } from "@better-captcha/qwik";
import { Prosopo, type ProsopoHandle, type RenderParameters } from "@better-captcha/qwik/provider/prosopo";
import { $, component$, useSignal } from "@builder.io/qwik";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export const ProsopoTest = component$<{ mode: CaptchaComponentMode }>(({ mode }) => {
	const controller = useCaptchaController<ProsopoHandle>();
	const options = useSignal<Omit<RenderParameters, "siteKey">>({
		theme: "light",
		callback: $((response: string) => {
			console.log("Prosopo CAPTCHA verified:", response);
		}),
		"error-callback": $((error: string) => {
			console.error("Prosopo CAPTCHA error:", error);
		}),
	});
	const response = useSignal<string | null>(null);
	const solved = useSignal<boolean>(false);

	const handleSolve$ = $((token: string) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	});

	return (
		<div>
			<RenderCaptcha
				mode={mode}
				provider="prosopo"
				component={Prosopo}
				controller={controller}
				options={options.value}
				sitekey="no_test_site_key"
				onSolve$={handleSolve$}
			/>
			{solved.value && <p id="captcha-solved">Captcha Solved!</p>}
			<button
				type="button"
				onClick$={() => {
					controller.value?.destroy();
				}}
			>
				Destroy
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.reset();
				}}
			>
				Reset
			</button>
			<button
				type="button"
				onClick$={() => {
					controller.value?.execute();
				}}
			>
				Execute
			</button>
			<button
				type="button"
				onClick$={async () => {
					await controller.value?.render();
				}}
			>
				Render
			</button>
			<button
				type="button"
				onClick$={() => {
					const captchaResponse = controller.value?.getResponse() || "No response";
					response.value = captchaResponse;
				}}
			>
				Get Response
			</button>
			<button
				type="button"
				onClick$={() => {
					const themes = ["light", "dark"];
					const currentTheme = options.value.theme || "light";
					const currentIndex = themes.indexOf(currentTheme as string);
					const nextIndex = (currentIndex + 1) % themes.length;
					options.value = {
						...options.value,
						theme: themes[nextIndex] as RenderParameters["theme"],
					};
				}}
			>
				Change Theme
			</button>
			{response.value && <p id="captcha-response">{response.value}</p>}
		</div>
	);
});

// apps/testing/solidjs/src/components/prosopo-test.tsx
import { createCaptchaController } from "@better-captcha/solidjs";
import { Prosopo, type ProsopoHandle } from "@better-captcha/solidjs/provider/prosopo";
import { createSignal } from "solid-js";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export function ProsopoTest(props: { mode: CaptchaComponentMode }) {
	const controller = createCaptchaController<ProsopoHandle>();
	const [response, setResponse] = createSignal<string>("");
	const [theme, setTheme] = createSignal<"light" | "dark" | "auto">("light");
	const [solved, setSolved] = createSignal<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = controller.handle()?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<h2>Prosopo Test</h2>

			<div>
				<RenderCaptcha
					mode={props.mode}
					provider="prosopo"
					component={Prosopo}
					controller={controller}
					sitekey="no_test_site_key"
					options={{
						theme: theme(),
						callback: (response: string) => {
							console.log("Prosopo CAPTCHA verified:", response);
							setResponse(response);
						},
						"error-callback": (error: unknown) => {
							console.error("Prosopo CAPTCHA error:", error);
						},
					}}
					onSolve={handleSolve}
				/>
				{solved() && <p id="captcha-solved">Captcha Solved!</p>}
			</div>

			<div>
				<button type="button" onClick={handleGetResponse}>
					Get Response
				</button>
				<button type="button" onClick={() => controller.handle()?.reset()}>
					Reset
				</button>
				<button type="button" onClick={() => controller.handle()?.execute()}>
					Execute
				</button>
				<button
					type="button"
					onClick={() => {
						const themes = ["light", "dark", "auto"];
						const currentIndex = themes.indexOf(theme() || "auto");
						const nextIndex = (currentIndex + 1) % themes.length;
						setTheme(themes[nextIndex] as "light" | "dark" | "auto");
					}}
				>
					Change Theme
				</button>
				<button type="button" onClick={() => controller.handle()?.destroy()}>
					Destroy
				</button>
			</div>

			{response() && <p id="captcha-response">{response()}</p>}
		</div>
	);
}
