// apps/testing/react/src/recaptcha-v3-test.tsx
import { ReCaptchaV3, type ReCaptchaV3Handle, type RenderParameters } from "@better-captcha/react/provider/recaptcha-v3";
import { useRef, useState } from "react";
import { RenderCaptcha, type CaptchaComponentMode } from "./render-captcha";

export function RecaptchaV3Test({ mode }: { mode: CaptchaComponentMode }) {
	const recaptchaRef = useRef<ReCaptchaV3Handle>(null);
	const [options, setOptions] = useState<RenderParameters>({
		action: "submit",
	});
	const [response, setResponse] = useState<string | null>(null);
	const [solved, setSolved] = useState<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = recaptchaRef.current?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha mode={mode} provider="recaptcha-v3" component={ReCaptchaV3} ref={recaptchaRef} sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI" options={options} onSolve={handleSolve} />
			{solved && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => recaptchaRef.current?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => recaptchaRef.current?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => recaptchaRef.current?.execute()}>
				Execute
			</button>
			<button type="button" onClick={() => recaptchaRef.current?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			<button
				type="button"
				onClick={() => {
					const actions = ["submit", "login", "register"];
					const currentIndex = actions.indexOf(options.action);
					const nextIndex = (currentIndex + 1) % actions.length;
					setOptions({ action: actions[nextIndex] ?? "submit" });
				}}
			>
				Change Action
			</button>
			{response && <p id="captcha-response">{response}</p>}
		</div>
	);
}

// apps/testing/solidjs/src/components/recaptcha-v3-test.tsx
import { createCaptchaController } from "@better-captcha/solidjs";
import {
	ReCaptchaV3,
	type ReCaptchaV3Handle,
	type RenderParameters,
} from "@better-captcha/solidjs/provider/recaptcha-v3";
import { createSignal } from "solid-js";
import { type CaptchaComponentMode, RenderCaptcha } from "./render-captcha";

export function RecaptchaV3Test(props: { mode: CaptchaComponentMode }) {
	const controller = createCaptchaController<ReCaptchaV3Handle>();
	const [options, setOptions] = createSignal<RenderParameters>({
		action: "submit",
	});
	const [response, setResponse] = createSignal<string | null>(null);
	const [solved, setSolved] = createSignal<boolean>(false);

	const handleGetResponse = () => {
		const captchaResponse = controller.handle()?.getResponse() || "No response";
		setResponse(captchaResponse);
	};

	const handleSolve = (token: string) => {
		setSolved(true);
		console.log("Captcha solved with token:", token);
	};

	return (
		<div>
			<RenderCaptcha
				mode={props.mode}
				provider="recaptcha-v3"
				component={ReCaptchaV3}
				controller={controller}
				sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
				options={options()}
				onSolve={handleSolve}
			/>
			{solved() && <p id="captcha-solved">Captcha Solved!</p>}
			<button type="button" onClick={() => controller.handle()?.destroy()}>
				Destroy
			</button>
			<button type="button" onClick={() => controller.handle()?.reset()}>
				Reset
			</button>
			<button type="button" onClick={() => controller.handle()?.execute()}>
				Execute
			</button>
			<button type="button" onClick={async () => await controller.handle()?.render()}>
				Render
			</button>
			<button type="button" onClick={handleGetResponse}>
				Get Response
			</button>
			<button
				type="button"
				onClick={() => {
					const actions = ["submit", "login", "register"];
					const currentIndex = actions.indexOf(options().action);
					const nextIndex = (currentIndex + 1) % actions.length;
					setOptions({ action: actions[nextIndex] });
				}}
			>
				Change Action
			</button>
			{response() && <p id="captcha-response">{response()}</p>}
		</div>
	);
}
