// apps/testing/vue/src/components/RenderCaptcha.vue
<template>
	<component
		:is="mode === 'dynamic' ? BetterCaptcha : component"
		ref="captchaRef"
		v-bind="componentProps"
	/>
</template>

<script setup lang="ts">
	import type { CaptchaHandle, CaptchaResponse, CaptchaState, ProviderName } from "@better-captcha/core";
	import { BetterCaptcha } from "@better-captcha/vue";
	import type { Component } from "vue";
	import { computed, ref, useAttrs } from "vue";

	export type CaptchaComponentMode = "dedicated" | "dynamic";

	defineOptions({ inheritAttrs: false });
	const props = defineProps<{
		mode: CaptchaComponentMode;
		provider: ProviderName;
		component: Component;
	}>();
	const attrs = useAttrs();
	const componentProps = computed(() => ({
		...attrs,
		...(props.mode === "dynamic" ? { provider: props.provider } : {}),
	}));

	const captchaRef = ref<CaptchaHandle<CaptchaResponse> | null>(null);

	defineExpose({
		execute: () => captchaRef.value?.execute() ?? Promise.resolve(),
		reset: () => captchaRef.value?.reset(),
		destroy: () => captchaRef.value?.destroy(),
		render: () => captchaRef.value?.render() ?? Promise.resolve(),
		getResponse: () => captchaRef.value?.getResponse(),
		getComponentState: (): CaptchaState =>
			captchaRef.value?.getComponentState() ?? { loading: false, error: null, ready: false },
	});
</script>

// apps/testing/svelte/src/components/render-captcha.svelte
<script lang="ts">
	import type { CaptchaState, ProviderName } from "@better-captcha/core";
	import { BetterCaptcha } from "@better-captcha/svelte";
	import type { Component } from "svelte";

	export type CaptchaComponentMode = "dedicated" | "dynamic";

	type Props = {
		mode: CaptchaComponentMode;
		provider: ProviderName;
		component: Component;
		[key: string]: unknown;
	};

	let { mode, provider, component: DedicatedComponent, ...rest }: Props = $props();

	let innerRef = $state<{
		execute(): Promise<void>;
		reset(): void;
		destroy(): void;
		getResponse(): unknown;
		getComponentState(): CaptchaState;
		render(): Promise<void>;
	}>();

	export const execute = () => innerRef?.execute() ?? Promise.resolve();
	export const reset = () => innerRef?.reset();
	export const destroy = () => innerRef?.destroy();
	export const getResponse = () => innerRef?.getResponse();
	export const getComponentState = () =>
		innerRef?.getComponentState() ?? { loading: false, error: null, ready: false };
	export const render = () => innerRef?.render() ?? Promise.resolve();
</script>

{#if mode === "dynamic"}
	<BetterCaptcha bind:this={innerRef} {provider} {...rest} />
{:else}
	<DedicatedComponent bind:this={innerRef} {...rest} />
{/if}
