// apps/testing/vue/src/components/TSecTest.vue
<template>
	<div>
		<h3>T-Sec Test</h3>
		<TSec ref="captchaRef" sitekey="189910271" :options="options" @ready="onReady" @error="onError" @solve="onSolve" />
		<p v-if="solved" id="captcha-solved">Captcha Solved!</p>
		<div style="margin-top: 10px">
			<button type="button" @click="handleDestroy">Destroy</button>
			<button type="button" @click="handleReset">Reset</button>
			<button type="button" @click="handleExecute">Execute</button>
			<button type="button" @click="handleRender">Render</button>
			<button type="button" @click="handleGetResponse">Get Response</button>
		</div>
		<p v-if="response" id="captcha-response">{{ JSON.stringify(response, null, "\t") }}</p>
		<p v-if="error" style="color: red">Error: {{ error.message }}</p>
	</div>
</template>

<script setup lang="ts">
import { TSec, type TSecHandle, type RenderParameters} from "@better-captcha/vue/provider/t-sec";
	import { ref } from "vue";

	const captchaRef = ref<TSecHandle | null>(null);
	const response = ref<ReturnType<TSecHandle["getResponse"]>>(null);
	const error = ref<Error | null>(null);
	const solved = ref<boolean>(false);

  const options = ref<RenderParameters>({
    userLanguage: "en",
  });

	const onReady = (handle: TSecHandle) => {
		console.log("Captcha ready!", handle);
	};

	const onError = (err: Error) => {
		error.value = err;
		console.error("Captcha error:", err);
	};

	const onSolve = (token: ReturnType<TSecHandle['getResponse']>) => {
		solved.value = true;
		console.log("Captcha solved with token:", token);
	};

	const handleDestroy = () => {
		captchaRef.value?.destroy();
	};

	const handleReset = () => {
		captchaRef.value?.reset();
		response.value = null;
	};

	const handleExecute = async () => {
		await captchaRef.value?.execute();
	};

	const handleRender = async () => {
		await captchaRef.value?.render();
	};

	const handleGetResponse = () => {
		const captchaResponse = captchaRef.value?.getResponse() ?? null;
		response.value = captchaResponse;
	};
</script>

// apps/testing/svelte/src/components/TSecTest.svelte
<script lang="ts">
	import type { TSecHandle } from "@better-captcha/svelte/provider/t-sec";
	import TSec from "@better-captcha/svelte/provider/t-sec";
	import { writable } from "svelte/store";

	let captchaRef: TSec | undefined;
	const response = writable<ReturnType<TSecHandle['getResponse']>>(null);
	const error = writable<Error | null>(null);
	const solved = writable<boolean>(false);

	function onReady(handle: TSecHandle) {
		console.log("Captcha ready!", handle);
	}

	function onError(err: Error) {
		error.set(err);
		console.error("Captcha error:", err);
	}

	function onSolve(token: string) {
		solved.set(true);
		console.log("Captcha solved with token:", token);
	}

	function handleDestroy() {
		captchaRef?.destroy();
	}

	function handleReset() {
		captchaRef?.reset();
		response.set(null);
	}

	async function handleExecute() {
		await captchaRef?.execute();
	}

	async function handleRender() {
		await captchaRef?.render();
	}

	function handleGetResponse() {
		const captchaResponse = captchaRef?.getResponse() ?? null;
		response.set(captchaResponse);
	}
</script>

<div>
	<h3>T-Sec Test</h3>
	<TSec bind:this={captchaRef} sitekey="189905409" options={{ userLanguage: "en" }} onready={onReady} onerror={onError} onSolve={onSolve} />
	{#if $solved}
		<p id="captcha-solved">Captcha Solved!</p>
	{/if}
	<div style="margin-top: 10px">
		<button type="button" onclick={handleDestroy}>Destroy</button>
		<button type="button" onclick={handleReset}>Reset</button>
		<button type="button" onclick={handleExecute}>Execute</button>
		<button type="button" onclick={handleRender}>Render</button>
		<button type="button" onclick={handleGetResponse}>Get Response</button>
	</div>
	{#if $response}
		<p id="captcha-response">{JSON.stringify($response, null, "\t")}</p>
	{/if}
	{#if $error}
		<p style="color: red">Error: {$error.message}</p>
	{/if}
</div>
