// apps/testing/qwik/src/routes/index.tsx
import { component$, useSignal } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { AltchaTest } from "../components/altcha-test";
import { CapWidgetTest } from "../components/cap-widget-test";
import { CaptchaFoxTest } from "../components/captcha-fox-test";
import { FriendlyCaptchaTest } from "../components/friendly-captcha-test";
import { GeetestTest } from "../components/geetest-test";
import { HCaptchaTest } from "../components/hcaptcha-test";
import { PrivateCaptchaTest } from "../components/private-captcha-test";
import { ProsopoTest } from "../components/prosopo-test";
import { RecaptchaTest } from "../components/recaptcha-test";
import { RecaptchaV3Test } from "../components/recaptcha-v3-test";
import { TSecTest } from "../components/tsec-test";
import { TurnstileTest } from "../components/turnstile-test";

export default component$(() => {
	const currentProvider = useSignal("turnstile");

	const providers = [
		{ key: "turnstile", name: "Turnstile", path: "/turnstile" },
		{ key: "hcaptcha", name: "hCaptcha", path: "/hcaptcha" },
		{ key: "recaptcha", name: "reCAPTCHA", path: "/recaptcha" },
		{ key: "recaptcha-v3", name: "reCAPTCHA v3", path: "/recaptcha-v3" },
		{ key: "friendly-captcha", name: "Friendly Captcha", path: "/friendly-captcha" },
		{ key: "private-captcha", name: "Private Captcha", path: "/private-captcha" },
		{ key: "captcha-fox", name: "Captcha Fox", path: "/captcha-fox" },
		{ key: "prosopo", name: "Prosopo", path: "/prosopo" },
		{ key: "cap-widget", name: "CapWidget", path: "/cap-widget" },
		{ key: "altcha", name: "Altcha", path: "/altcha" },
		{ key: "geetest", name: "Geetest", path: "/geetest" },
		{ key: "t-sec", name: "T-Sec", path: "/t-sec" },
	];

	return (
		<>
			<h1>Qwik Captcha Testing</h1>

			<div>
				<h2>Select Provider:</h2>
				{providers.map((provider) => (
					<button
						key={provider.key}
						type="button"
						onClick$={() => {
							currentProvider.value = provider.key;
						}}
						style={{ margin: "5px", padding: "10px" }}
					>
						{provider.name}
					</button>
				))}
			</div>

			<div style={{ "margin-top": "20px" }} id="captcha-container">
				{currentProvider.value === "turnstile" && <TurnstileTest />}
				{currentProvider.value === "hcaptcha" && <HCaptchaTest />}
				{currentProvider.value === "recaptcha" && <RecaptchaTest />}
				{currentProvider.value === "recaptcha-v3" && <RecaptchaV3Test />}
				{currentProvider.value === "friendly-captcha" && <FriendlyCaptchaTest />}
				{currentProvider.value === "private-captcha" && <PrivateCaptchaTest />}
				{currentProvider.value === "captcha-fox" && <CaptchaFoxTest />}
				{currentProvider.value === "prosopo" && <ProsopoTest />}
				{currentProvider.value === "cap-widget" && <CapWidgetTest />}
				{currentProvider.value === "altcha" && <AltchaTest />}
				{currentProvider.value === "geetest" && <GeetestTest />}
				{currentProvider.value === "t-sec" && <TSecTest />}
			</div>
		</>
	);
});

export const head: DocumentHead = {
	title: "Qwik Captcha Testing",
	meta: [
		{
			name: "description",
			content: "Testing Better Captcha with Qwik",
		},
	],
};

// apps/testing/solidjs/src/routes/index.tsx
import { Title } from "@solidjs/meta";
import { clientOnly } from "@solidjs/start";
import { createSignal } from "solid-js";
import { AltchaTest } from "../components/altcha-test";
import { CapWidgetTest } from "../components/cap-widget-test";
import { CaptchaFoxTest } from "../components/captcha-fox-test";
import { FriendlyCaptchaTest } from "../components/friendly-captcha-test";
import { GeetestTest } from "../components/geetest-test";
import { HCaptchaTest } from "../components/hcaptcha-test";
import { PrivateCaptchaTest } from "../components/private-captcha-test";
import { ProsopoTest } from "../components/prosopo-test";
import { RecaptchaTest } from "../components/recaptcha-test";
import { RecaptchaV3Test } from "../components/recaptcha-v3-test";
import { TSecTest } from "../components/tsec-test";
import { TurnstileTest } from "../components/turnstile-test";

export default clientOnly(async () => ({ default: Home }), { lazy: true });

export function Home() {
	const [currentProvider, setCurrentProvider] = createSignal("turnstile");

	const providers = [
		{ key: "turnstile", name: "Turnstile", path: "/turnstile" },
		{ key: "hcaptcha", name: "hCaptcha", path: "/hcaptcha" },
		{ key: "recaptcha", name: "reCAPTCHA", path: "/recaptcha" },
		{ key: "recaptcha-v3", name: "reCAPTCHA v3", path: "/recaptcha-v3" },
		{ key: "friendly-captcha", name: "Friendly Captcha", path: "/friendly-captcha" },
		{ key: "private-captcha", name: "Private Captcha", path: "/private-captcha" },
		{ key: "captcha-fox", name: "Captcha Fox", path: "/captcha-fox" },
		{ key: "prosopo", name: "Prosopo", path: "/prosopo" },
		{ key: "cap-widget", name: "CapWidget", path: "/cap-widget" },
		{ key: "altcha", name: "Altcha", path: "/altcha" },
		{ key: "geetest", name: "Geetest", path: "/geetest" },
		{ key: "t-sec", name: "T-Sec", path: "/t-sec" },
	];

	return (
		<main>
			<Title>Solid Captcha Testing</Title>
			<h1>Solid Captcha Testing</h1>

			<div>
				<h2>Select Provider:</h2>
				{providers.map((provider) => (
					<button
						type="button"
						onClick={() => setCurrentProvider(provider.key)}
						style={{ margin: "5px", padding: "10px" }}
					>
						{provider.name}
					</button>
				))}
			</div>

			<div style={{ "margin-top": "20px" }}>
				{currentProvider() === "turnstile" && <TurnstileTest />}
				{currentProvider() === "hcaptcha" && <HCaptchaTest />}
				{currentProvider() === "recaptcha" && <RecaptchaTest />}
				{currentProvider() === "recaptcha-v3" && <RecaptchaV3Test />}
				{currentProvider() === "friendly-captcha" && <FriendlyCaptchaTest />}
				{currentProvider() === "private-captcha" && <PrivateCaptchaTest />}
				{currentProvider() === "captcha-fox" && <CaptchaFoxTest />}
				{currentProvider() === "prosopo" && <ProsopoTest />}
				{currentProvider() === "cap-widget" && <CapWidgetTest />}
				{currentProvider() === "altcha" && <AltchaTest />}
				{currentProvider() === "geetest" && <GeetestTest />}
				{currentProvider() === "t-sec" && <TSecTest />}
			</div>
		</main>
	);
}
